### ISSUE TITLE
How can I order my query?

### ISSUE THREAD

**Issue by dettmar** [mirabalj/sequelize-paginate-cursor#2]
I've tried several ordering methods from the [Sequelize docs](http://docs.sequelizejs.com/manual/tutorial/querying.html#ordering) but none of them seem to work.
Including:
```
{
  order: ['lastSeen', 'DESC'],
  order: '"lastSeen" DESC',
  order: sequelize.literal('"lastSeen" DESC'),
  ...
}
```
But the actual query performed is always ending with `ORDER BY id DESC`.
Is there any way to solve this?

**Comment by iamjinme** [comment]
Since the pagination work with a 'keyPaginated', this key is necessarily used to order the results. This is necessary to return correctly the 'nextCursor' and avoid conflicts. You can change this key by your preferred column.

**Comment by dettmar** [comment]
@mirabalj all right, thank you! And by adding `reverse` I can then choose the order I want?

**Comment by iamjinme** [comment]
Yeap, 'reverse' option change the order of paginate. Good luck!
